"""Generated portable Conversation API; update through the canonical schema."""

# Generated by scripts/generate_contracts.py; do not edit.
from datetime import datetime
from enum import StrEnum
from typing import Annotated, ClassVar, Final, Literal
from uuid import UUID

from pydantic import ConfigDict, Field

from secretary_service.models import FrozenModel

CONVERSATION_CONTRACT_VERSION: Final = "1.0.0"


class ParticipantKind(StrEnum):
    USER = "user"
    AGENT = "agent"


class DeviceKind(StrEnum):
    IOS = "ios"
    MAC = "mac"
    WEB = "web"
    CHANNEL = "channel"


class ChannelKind(StrEnum):
    OPENCLAW_WEBCHAT = "openclaw_webchat"
    TELEGRAM = "telegram"
    IMESSAGE = "imessage"
    EMAIL = "email"


class ChannelBindingState(StrEnum):
    ACTIVE = "active"
    REVOKED = "revoked"


class ConversationState(StrEnum):
    ACTIVE = "active"
    CANCELLED = "cancelled"
    COMPLETED = "completed"


class ConversationEventKind(StrEnum):
    TRANSCRIPT_PARTIAL = "transcript_partial"
    TRANSCRIPT_FINAL = "transcript_final"
    ATTACHMENT = "attachment"
    TOOL_RESULT = "tool_result"
    CANCELLATION = "cancellation"
    RESUME = "resume"
    ERROR = "error"


class ToolResultStatus(StrEnum):
    OK = "ok"
    ERROR = "error"


class ConversationParticipant(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    participant_id: UUID
    kind: ParticipantKind
    display_name: str
    created_at: datetime


class ConversationDevice(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    device_id: UUID
    participant_id: UUID
    kind: DeviceKind
    name: str
    created_at: datetime


class ChannelBinding(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    binding_id: UUID
    conversation_id: UUID
    channel_kind: ChannelKind
    external_channel_id: str
    external_user_id: str
    bound_at: datetime
    state: ChannelBindingState


class Conversation(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    conversation_id: UUID
    title: str
    participant_ids: list[UUID]
    device_ids: list[UUID]
    created_at: datetime
    state: ConversationState


class TranscriptPartial(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["transcript_partial"] = "transcript_partial"
    turn_id: UUID
    text: str
    is_final: Literal[False] = False


class TranscriptFinal(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["transcript_final"] = "transcript_final"
    turn_id: UUID
    text: str
    is_final: Literal[True] = True


class Attachment(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["attachment"] = "attachment"
    attachment_id: UUID
    mime_type: str
    size_bytes: int
    reference: str


class ToolResult(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["tool_result"] = "tool_result"
    tool_call_id: str
    tool_name: str
    status: ToolResultStatus
    result_reference: str


class Cancellation(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["cancellation"] = "cancellation"
    turn_id: UUID
    reason: str


class Resume(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["resume"] = "resume"
    turn_id: UUID
    resume_from_turn_id: UUID


class ConversationError(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["error"] = "error"
    code: str
    message: str
    retryable: bool


ConversationEventPayload = Annotated[
    TranscriptPartial
    | TranscriptFinal
    | Attachment
    | ToolResult
    | Cancellation
    | Resume
    | ConversationError,
    Field(discriminator="kind"),
]


class ConversationEvent(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    event_id: UUID
    conversation_id: UUID
    participant_id: UUID
    device_id: UUID
    sequence: int
    occurred_at: datetime
    kind: ConversationEventKind
    payload: ConversationEventPayload


class ConversationRejection(StrEnum):
    UNKNOWN_CONVERSATION = "unknown_conversation"
    CONVERSATION_CLOSED = "conversation_closed"
    DUPLICATE_EVENT = "duplicate_event"
    OUT_OF_ORDER = "out_of_order"
    FOREIGN_PARTICIPANT = "foreign_participant"
    FOREIGN_DEVICE = "foreign_device"
    DEVICE_PARTICIPANT_MISMATCH = "device_participant_mismatch"
    KIND_MISMATCH = "kind_mismatch"
    FINAL_WITHOUT_PARTIAL = "final_without_partial"
    TURN_CLOSED = "turn_closed"
    EVENT_AFTER_CANCELLATION = "event_after_cancellation"
    RESUME_WITHOUT_CANCELLATION = "resume_without_cancellation"


class ConversationAcceptance(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    accepted: bool
    rejection: ConversationRejection | None
    next_sequence: int


class ConversationJournal:
    """Ordering gate for a single conversation's event stream."""

    def __init__(self, conversation: Conversation, devices: list[ConversationDevice]) -> None:
        """Bind the journal to one conversation and its enrolled devices."""
        self._conversation: Conversation = conversation
        self._devices: dict[UUID, ConversationDevice] = {
            device.device_id: device for device in devices
        }
        self._next_sequence: int = 1
        self._seen_event_ids: set[UUID] = set()
        self._open_turn_id: UUID | None = None
        self._cancelled_turn_id: UUID | None = None

    def accept(self, event: ConversationEvent) -> ConversationAcceptance:
        """Accept one ordered event or reject it with a typed reason."""
        rejection = self._envelope_rejection(event)
        if rejection is not None:
            return self._reject(rejection)
        rejection = self._payload_rejection(event)
        if rejection is not None:
            return self._reject(rejection)
        self._seen_event_ids.add(event.event_id)
        self._next_sequence += 1
        self._apply_payload_state(event)
        return ConversationAcceptance(
            accepted=True, rejection=None, next_sequence=self._next_sequence
        )

    def _reject(self, rejection: ConversationRejection) -> ConversationAcceptance:
        return ConversationAcceptance(
            accepted=False,
            rejection=rejection,
            next_sequence=self._next_sequence,
        )

    def _envelope_rejection(self, event: ConversationEvent) -> ConversationRejection | None:
        if event.conversation_id != self._conversation.conversation_id:
            return ConversationRejection.UNKNOWN_CONVERSATION
        if self._conversation.state != ConversationState.ACTIVE:
            return ConversationRejection.CONVERSATION_CLOSED
        if event.event_id in self._seen_event_ids:
            return ConversationRejection.DUPLICATE_EVENT
        if event.participant_id not in self._conversation.participant_ids:
            return ConversationRejection.FOREIGN_PARTICIPANT
        device = self._devices.get(event.device_id)
        if device is None or event.device_id not in self._conversation.device_ids:
            return ConversationRejection.FOREIGN_DEVICE
        if device.participant_id != event.participant_id:
            return ConversationRejection.DEVICE_PARTICIPANT_MISMATCH
        if event.kind.value != event.payload.kind:
            return ConversationRejection.KIND_MISMATCH
        if event.sequence != self._next_sequence:
            return ConversationRejection.OUT_OF_ORDER
        return None

    def _payload_rejection(self, event: ConversationEvent) -> ConversationRejection | None:
        payload = event.payload
        if isinstance(payload, TranscriptPartial | TranscriptFinal):
            if self._cancelled_turn_id is not None and payload.turn_id == self._cancelled_turn_id:
                return ConversationRejection.EVENT_AFTER_CANCELLATION
            if self._open_turn_id is None:
                if isinstance(payload, TranscriptFinal):
                    return ConversationRejection.FINAL_WITHOUT_PARTIAL
            elif payload.turn_id != self._open_turn_id:
                return ConversationRejection.TURN_CLOSED
        elif isinstance(payload, Resume):
            if (
                self._cancelled_turn_id is None
                or payload.resume_from_turn_id != self._cancelled_turn_id
            ):
                return ConversationRejection.RESUME_WITHOUT_CANCELLATION
        return None

    def _apply_payload_state(self, event: ConversationEvent) -> None:
        payload = event.payload
        if isinstance(payload, TranscriptPartial):
            self._open_turn_id = payload.turn_id
        elif isinstance(payload, TranscriptFinal):
            self._open_turn_id = None
        elif isinstance(payload, Cancellation):
            self._open_turn_id = None
            self._cancelled_turn_id = payload.turn_id
        elif isinstance(payload, Resume):
            self._open_turn_id = payload.turn_id
            self._cancelled_turn_id = None
