from collections.abc import Callable, Iterable
from sqlite3 import DatabaseError as DatabaseError
from sqlite3 import IntegrityError as IntegrityError
from types import TracebackType
from typing import Self

type SqlValue = str | int | float | bytes | None

class Cursor:
    def fetchone(self) -> tuple[str | bytes, ...] | None: ...
    def fetchall(self) -> list[tuple[str | bytes, ...]]: ...

class Connection:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def execute(self, sql: str, parameters: Iterable[SqlValue] = ...) -> Cursor: ...
    def executemany(self, sql: str, parameters: Iterable[Iterable[SqlValue]]) -> Cursor: ...
    def executescript(self, sql_script: str) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def backup(self, target: Connection) -> None: ...
    def create_function(self, name: str, narg: int, func: Callable[[], int]) -> None: ...

def connect(database: str, *, timeout: float = ...) -> Connection: ...
