#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13,<3.14"
# dependencies = ["pydantic>=2.11,<3"]
# ///
#
# --- How to run ---
# 1. Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh
# 2. Generate: uv run scripts/generate_contracts.py
# 3. Verify only: uv run scripts/generate_contracts.py --check
# ------------------

"""Generate language-specific contract bindings from the canonical schemas."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import ClassVar, Final

from pydantic import BaseModel, ConfigDict, Field

ROOT: Final = Path(__file__).resolve().parents[1]
SCHEMA_PATH: Final = ROOT / "contracts" / "v1" / "secretary-api.schema.json"
PYTHON_PATH: Final = (
    ROOT / "mac" / "secretary_service" / "src" / "secretary_service" / "contract_version.py"
)
SWIFT_PATH: Final = (
    ROOT / "ios" / "SecretaryApp" / "SecretaryApp" / "Contract" / "ContractVersion.generated.swift"
)
CONVERSATION_SCHEMA_PATH: Final = ROOT / "contracts" / "v1" / "conversation-api.schema.json"
CONVERSATION_PYTHON_PATH: Final = (
    ROOT / "mac" / "secretary_service" / "src" / "secretary_service" / "conversation_api.py"
)
CONVERSATION_SWIFT_PATH: Final = (
    ROOT / "ios" / "SecretaryApp" / "SecretaryApp" / "Contract" / "ConversationAPI.generated.swift"
)

CONVERSATION_DEFS: Final = frozenset(
    {
        "participant",
        "device",
        "channel_binding",
        "conversation",
        "conversation_event",
        "transcript_partial",
        "transcript_final",
        "attachment",
        "tool_result",
        "cancellation",
        "resume",
        "error",
    }
)


class ContractVersionDefinition(BaseModel):
    """Version definition parsed from the canonical schema."""

    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True)

    const: str = Field(pattern=r"^[0-9]+\.[0-9]+\.[0-9]+$")


class ContractProperties(BaseModel):
    """Contract properties required by code generation."""

    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True)

    contract_version: ContractVersionDefinition


class ContractSchema(BaseModel):
    """Minimal typed view of the canonical JSON Schema."""

    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True)

    properties: ContractProperties


class ConversationSchema(BaseModel):
    """Typed view of the canonical conversation JSON Schema."""

    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True)

    properties: ContractProperties
    defs: dict[str, object] = Field(alias="$defs")


def generated_sources(version: str) -> tuple[str, str]:
    """Render deterministic Python and Swift version sources."""
    python_source = (
        '"""Generated contract version; update through the canonical schema."""\n\n'
        "# Generated by scripts/generate_contracts.py; do not edit.\n"
        "from typing import Final\n\n"
        f'CONTRACT_VERSION: Final = "{version}"\n'
    )
    swift_source = (
        "// Generated by scripts/generate_contracts.py; do not edit.\n"
        "public struct SecretaryContractVersion: Equatable, Sendable {\n"
        "    public static let current = SecretaryContractVersion()\n"
        f'    public let rawValue = "{version}"\n\n'
        "    private init() {}\n"
        "}\n"
    )
    return python_source, swift_source


def conversation_sources(version: str) -> tuple[str, str]:
    """Render deterministic Python and Swift conversation API sources."""
    return (
        _CONVERSATION_PYTHON_TEMPLATE.replace("__VERSION__", version),
        _CONVERSATION_SWIFT_TEMPLATE.replace("__VERSION__", version),
    )


def update_source(path: Path, content: str, *, check: bool) -> bool:
    """Write one generated source or report whether it is current."""
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    """Generate both language bindings from the canonical schemas."""
    unexpected_arguments = set(sys.argv[1:]) - {"--check"}
    if unexpected_arguments:
        sys.stderr.write(f"unexpected arguments: {sorted(unexpected_arguments)}\n")
        return 2

    schema = ContractSchema.model_validate_json(SCHEMA_PATH.read_bytes())
    conversation_schema = ConversationSchema.model_validate_json(
        CONVERSATION_SCHEMA_PATH.read_bytes()
    )
    if set(conversation_schema.defs) != CONVERSATION_DEFS:
        sys.stderr.write("conversation schema defs drifted from the generated bindings\n")
        return 2

    version = schema.properties.contract_version.const
    conversation_version = conversation_schema.properties.contract_version.const
    if conversation_version != version:
        sys.stderr.write("conversation schema version drifted from the transport schema\n")
        return 2

    python_source, swift_source = generated_sources(version)
    conversation_python, conversation_swift = conversation_sources(conversation_version)
    check = "--check" in sys.argv[1:]
    current = all(
        (
            update_source(PYTHON_PATH, python_source, check=check),
            update_source(SWIFT_PATH, swift_source, check=check),
            update_source(CONVERSATION_PYTHON_PATH, conversation_python, check=check),
            update_source(CONVERSATION_SWIFT_PATH, conversation_swift, check=check),
        )
    )
    if check and not current:
        sys.stderr.write("generated contract sources are stale\n")
        return 1
    return 0


_CONVERSATION_PYTHON_TEMPLATE = '''\
"""Generated portable Conversation API; update through the canonical schema."""

# Generated by scripts/generate_contracts.py; do not edit.
from datetime import datetime
from enum import StrEnum
from typing import Annotated, ClassVar, Final, Literal
from uuid import UUID

from pydantic import ConfigDict, Field

from secretary_service.models import FrozenModel

CONVERSATION_CONTRACT_VERSION: Final = "__VERSION__"


class ParticipantKind(StrEnum):
    USER = "user"
    AGENT = "agent"


class DeviceKind(StrEnum):
    IOS = "ios"
    MAC = "mac"
    WEB = "web"
    CHANNEL = "channel"


class ChannelKind(StrEnum):
    OPENCLAW_WEBCHAT = "openclaw_webchat"
    TELEGRAM = "telegram"
    IMESSAGE = "imessage"
    EMAIL = "email"


class ChannelBindingState(StrEnum):
    ACTIVE = "active"
    REVOKED = "revoked"


class ConversationState(StrEnum):
    ACTIVE = "active"
    CANCELLED = "cancelled"
    COMPLETED = "completed"


class ConversationEventKind(StrEnum):
    TRANSCRIPT_PARTIAL = "transcript_partial"
    TRANSCRIPT_FINAL = "transcript_final"
    ATTACHMENT = "attachment"
    TOOL_RESULT = "tool_result"
    CANCELLATION = "cancellation"
    RESUME = "resume"
    ERROR = "error"


class ToolResultStatus(StrEnum):
    OK = "ok"
    ERROR = "error"


class ConversationParticipant(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    participant_id: UUID
    kind: ParticipantKind
    display_name: str
    created_at: datetime


class ConversationDevice(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    device_id: UUID
    participant_id: UUID
    kind: DeviceKind
    name: str
    created_at: datetime


class ChannelBinding(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    binding_id: UUID
    conversation_id: UUID
    channel_kind: ChannelKind
    external_channel_id: str
    external_user_id: str
    bound_at: datetime
    state: ChannelBindingState


class Conversation(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    conversation_id: UUID
    title: str
    participant_ids: list[UUID]
    device_ids: list[UUID]
    created_at: datetime
    state: ConversationState


class TranscriptPartial(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["transcript_partial"] = "transcript_partial"
    turn_id: UUID
    text: str
    is_final: Literal[False] = False


class TranscriptFinal(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["transcript_final"] = "transcript_final"
    turn_id: UUID
    text: str
    is_final: Literal[True] = True


class Attachment(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["attachment"] = "attachment"
    attachment_id: UUID
    mime_type: str
    size_bytes: int
    reference: str


class ToolResult(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["tool_result"] = "tool_result"
    tool_call_id: str
    tool_name: str
    status: ToolResultStatus
    result_reference: str


class Cancellation(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["cancellation"] = "cancellation"
    turn_id: UUID
    reason: str


class Resume(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["resume"] = "resume"
    turn_id: UUID
    resume_from_turn_id: UUID


class ConversationError(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    kind: Literal["error"] = "error"
    code: str
    message: str
    retryable: bool


ConversationEventPayload = Annotated[
    TranscriptPartial
    | TranscriptFinal
    | Attachment
    | ToolResult
    | Cancellation
    | Resume
    | ConversationError,
    Field(discriminator="kind"),
]


class ConversationEvent(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    event_id: UUID
    conversation_id: UUID
    participant_id: UUID
    device_id: UUID
    sequence: int
    occurred_at: datetime
    kind: ConversationEventKind
    payload: ConversationEventPayload


class ConversationRejection(StrEnum):
    UNKNOWN_CONVERSATION = "unknown_conversation"
    CONVERSATION_CLOSED = "conversation_closed"
    DUPLICATE_EVENT = "duplicate_event"
    OUT_OF_ORDER = "out_of_order"
    FOREIGN_PARTICIPANT = "foreign_participant"
    FOREIGN_DEVICE = "foreign_device"
    DEVICE_PARTICIPANT_MISMATCH = "device_participant_mismatch"
    KIND_MISMATCH = "kind_mismatch"
    FINAL_WITHOUT_PARTIAL = "final_without_partial"
    TURN_CLOSED = "turn_closed"
    EVENT_AFTER_CANCELLATION = "event_after_cancellation"
    RESUME_WITHOUT_CANCELLATION = "resume_without_cancellation"


class ConversationAcceptance(FrozenModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(frozen=True, extra="forbid")

    accepted: bool
    rejection: ConversationRejection | None
    next_sequence: int


class ConversationJournal:
    """Ordering gate for a single conversation's event stream."""

    def __init__(self, conversation: Conversation, devices: list[ConversationDevice]) -> None:
        """Bind the journal to one conversation and its enrolled devices."""
        self._conversation: Conversation = conversation
        self._devices: dict[UUID, ConversationDevice] = {
            device.device_id: device for device in devices
        }
        self._next_sequence: int = 1
        self._seen_event_ids: set[UUID] = set()
        self._open_turn_id: UUID | None = None
        self._cancelled_turn_id: UUID | None = None

    def accept(self, event: ConversationEvent) -> ConversationAcceptance:
        """Accept one ordered event or reject it with a typed reason."""
        rejection = self._envelope_rejection(event)
        if rejection is not None:
            return self._reject(rejection)
        rejection = self._payload_rejection(event)
        if rejection is not None:
            return self._reject(rejection)
        self._seen_event_ids.add(event.event_id)
        self._next_sequence += 1
        self._apply_payload_state(event)
        return ConversationAcceptance(
            accepted=True, rejection=None, next_sequence=self._next_sequence
        )

    def _reject(self, rejection: ConversationRejection) -> ConversationAcceptance:
        return ConversationAcceptance(
            accepted=False,
            rejection=rejection,
            next_sequence=self._next_sequence,
        )

    def _envelope_rejection(self, event: ConversationEvent) -> ConversationRejection | None:
        if event.conversation_id != self._conversation.conversation_id:
            return ConversationRejection.UNKNOWN_CONVERSATION
        if self._conversation.state != ConversationState.ACTIVE:
            return ConversationRejection.CONVERSATION_CLOSED
        if event.event_id in self._seen_event_ids:
            return ConversationRejection.DUPLICATE_EVENT
        if event.participant_id not in self._conversation.participant_ids:
            return ConversationRejection.FOREIGN_PARTICIPANT
        device = self._devices.get(event.device_id)
        if device is None or event.device_id not in self._conversation.device_ids:
            return ConversationRejection.FOREIGN_DEVICE
        if device.participant_id != event.participant_id:
            return ConversationRejection.DEVICE_PARTICIPANT_MISMATCH
        if event.kind.value != event.payload.kind:
            return ConversationRejection.KIND_MISMATCH
        if event.sequence != self._next_sequence:
            return ConversationRejection.OUT_OF_ORDER
        return None

    def _payload_rejection(self, event: ConversationEvent) -> ConversationRejection | None:
        payload = event.payload
        if isinstance(payload, TranscriptPartial | TranscriptFinal):
            if self._cancelled_turn_id is not None and payload.turn_id == self._cancelled_turn_id:
                return ConversationRejection.EVENT_AFTER_CANCELLATION
            if self._open_turn_id is None:
                if isinstance(payload, TranscriptFinal):
                    return ConversationRejection.FINAL_WITHOUT_PARTIAL
            elif payload.turn_id != self._open_turn_id:
                return ConversationRejection.TURN_CLOSED
        elif isinstance(payload, Resume):
            if (
                self._cancelled_turn_id is None
                or payload.resume_from_turn_id != self._cancelled_turn_id
            ):
                return ConversationRejection.RESUME_WITHOUT_CANCELLATION
        return None

    def _apply_payload_state(self, event: ConversationEvent) -> None:
        payload = event.payload
        if isinstance(payload, TranscriptPartial):
            self._open_turn_id = payload.turn_id
        elif isinstance(payload, TranscriptFinal):
            self._open_turn_id = None
        elif isinstance(payload, Cancellation):
            self._open_turn_id = None
            self._cancelled_turn_id = payload.turn_id
        elif isinstance(payload, Resume):
            self._open_turn_id = payload.turn_id
            self._cancelled_turn_id = None
'''


_CONVERSATION_SWIFT_TEMPLATE = """\
// Generated by scripts/generate_contracts.py; do not edit.
import Foundation

public enum ParticipantKind: String, Codable, Equatable, Sendable {
    case user = "user"
    case agent = "agent"
}

public enum DeviceKind: String, Codable, Equatable, Sendable {
    case ios = "ios"
    case mac = "mac"
    case web = "web"
    case channel = "channel"
}

public enum ChannelKind: String, Codable, Equatable, Sendable {
    case openclawWebchat = "openclaw_webchat"
    case telegram = "telegram"
    case imessage = "imessage"
    case email = "email"
}

public enum ChannelBindingState: String, Codable, Equatable, Sendable {
    case active = "active"
    case revoked = "revoked"
}

public enum ConversationState: String, Codable, Equatable, Sendable {
    case active = "active"
    case cancelled = "cancelled"
    case completed = "completed"
}

public enum ConversationEventKind: String, Codable, Equatable, Sendable {
    case transcriptPartial = "transcript_partial"
    case transcriptFinal = "transcript_final"
    case attachment = "attachment"
    case toolResult = "tool_result"
    case cancellation = "cancellation"
    case resume = "resume"
    case error = "error"
}

public enum ToolResultStatus: String, Codable, Equatable, Sendable {
    case ok = "ok"
    case error = "error"
}

public struct ConversationParticipant: Codable, Equatable, Sendable {
    public let participantId: UUID
    public let kind: ParticipantKind
    public let displayName: String
    public let createdAt: Date

    private enum CodingKeys: String, CodingKey {
        case participantId = "participant_id"
        case kind
        case displayName = "display_name"
        case createdAt = "created_at"
    }
}

public struct ConversationDevice: Codable, Equatable, Sendable {
    public let deviceId: UUID
    public let participantId: UUID
    public let kind: DeviceKind
    public let name: String
    public let createdAt: Date

    private enum CodingKeys: String, CodingKey {
        case deviceId = "device_id"
        case participantId = "participant_id"
        case kind
        case name
        case createdAt = "created_at"
    }
}

public struct ChannelBinding: Codable, Equatable, Sendable {
    public let bindingId: UUID
    public let conversationId: UUID
    public let channelKind: ChannelKind
    public let externalChannelId: String
    public let externalUserId: String
    public let boundAt: Date
    public let state: ChannelBindingState

    private enum CodingKeys: String, CodingKey {
        case bindingId = "binding_id"
        case conversationId = "conversation_id"
        case channelKind = "channel_kind"
        case externalChannelId = "external_channel_id"
        case externalUserId = "external_user_id"
        case boundAt = "bound_at"
        case state
    }
}

public struct Conversation: Codable, Equatable, Sendable {
    public let conversationId: UUID
    public let title: String
    public let participantIds: [UUID]
    public let deviceIds: [UUID]
    public let createdAt: Date
    public let state: ConversationState

    private enum CodingKeys: String, CodingKey {
        case conversationId = "conversation_id"
        case title
        case participantIds = "participant_ids"
        case deviceIds = "device_ids"
        case createdAt = "created_at"
        case state
    }
}

public struct TranscriptPartial: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let text: String
    public let isFinal: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case text
        case isFinal = "is_final"
    }
}

public struct TranscriptFinal: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let text: String
    public let isFinal: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case text
        case isFinal = "is_final"
    }
}

public struct Attachment: Codable, Equatable, Sendable {
    public let kind: String
    public let attachmentId: UUID
    public let mimeType: String
    public let sizeBytes: Int
    public let reference: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case attachmentId = "attachment_id"
        case mimeType = "mime_type"
        case sizeBytes = "size_bytes"
        case reference
    }
}

public struct ToolResult: Codable, Equatable, Sendable {
    public let kind: String
    public let toolCallId: String
    public let toolName: String
    public let status: ToolResultStatus
    public let resultReference: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case toolCallId = "tool_call_id"
        case toolName = "tool_name"
        case status
        case resultReference = "result_reference"
    }
}

public struct Cancellation: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let reason: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case reason
    }
}

public struct Resume: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let resumeFromTurnId: UUID

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case resumeFromTurnId = "resume_from_turn_id"
    }
}

public struct ConversationError: Codable, Equatable, Sendable {
    public let kind: String
    public let code: String
    public let message: String
    public let retryable: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case code
        case message
        case retryable
    }
}

public enum ConversationEventPayload: Codable, Equatable, Sendable {
    case transcriptPartial(TranscriptPartial)
    case transcriptFinal(TranscriptFinal)
    case attachment(Attachment)
    case toolResult(ToolResult)
    case cancellation(Cancellation)
    case resume(Resume)
    case error(ConversationError)

    public var kind: String {
        switch self {
        case .transcriptPartial: return "transcript_partial"
        case .transcriptFinal: return "transcript_final"
        case .attachment: return "attachment"
        case .toolResult: return "tool_result"
        case .cancellation: return "cancellation"
        case .resume: return "resume"
        case .error: return "error"
        }
    }

    private enum CodingKeys: String, CodingKey {
        case kind
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let kind = try container.decode(String.self, forKey: .kind)
        switch kind {
        case "transcript_partial":
            self = .transcriptPartial(try TranscriptPartial(from: decoder))
        case "transcript_final":
            self = .transcriptFinal(try TranscriptFinal(from: decoder))
        case "attachment":
            self = .attachment(try Attachment(from: decoder))
        case "tool_result":
            self = .toolResult(try ToolResult(from: decoder))
        case "cancellation":
            self = .cancellation(try Cancellation(from: decoder))
        case "resume":
            self = .resume(try Resume(from: decoder))
        case "error":
            self = .error(try ConversationError(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .kind,
                in: container,
                debugDescription: "unknown conversation payload kind: \\(kind)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .transcriptPartial(let payload):
            try payload.encode(to: encoder)
        case .transcriptFinal(let payload):
            try payload.encode(to: encoder)
        case .attachment(let payload):
            try payload.encode(to: encoder)
        case .toolResult(let payload):
            try payload.encode(to: encoder)
        case .cancellation(let payload):
            try payload.encode(to: encoder)
        case .resume(let payload):
            try payload.encode(to: encoder)
        case .error(let payload):
            try payload.encode(to: encoder)
        }
    }
}

public struct ConversationEvent: Codable, Equatable, Sendable {
    public let eventId: UUID
    public let conversationId: UUID
    public let participantId: UUID
    public let deviceId: UUID
    public let sequence: Int
    public let occurredAt: Date
    public let kind: ConversationEventKind
    public let payload: ConversationEventPayload

    private enum CodingKeys: String, CodingKey {
        case eventId = "event_id"
        case conversationId = "conversation_id"
        case participantId = "participant_id"
        case deviceId = "device_id"
        case sequence
        case occurredAt = "occurred_at"
        case kind
        case payload
    }
}

public enum ConversationRejection: String, Codable, Equatable, Sendable {
    case unknownConversation = "unknown_conversation"
    case conversationClosed = "conversation_closed"
    case duplicateEvent = "duplicate_event"
    case outOfOrder = "out_of_order"
    case foreignParticipant = "foreign_participant"
    case foreignDevice = "foreign_device"
    case deviceParticipantMismatch = "device_participant_mismatch"
    case kindMismatch = "kind_mismatch"
    case finalWithoutPartial = "final_without_partial"
    case turnClosed = "turn_closed"
    case eventAfterCancellation = "event_after_cancellation"
    case resumeWithoutCancellation = "resume_without_cancellation"
}

public struct ConversationAcceptance: Codable, Equatable, Sendable {
    public let accepted: Bool
    public let rejection: ConversationRejection?
    public let nextSequence: Int

    private enum CodingKeys: String, CodingKey {
        case accepted
        case rejection
        case nextSequence = "next_sequence"
    }
}

public final class ConversationJournal {
    private let conversation: Conversation
    private let devices: [UUID: ConversationDevice]
    private var nextSequence: Int
    private var seenEventIDs: Set<UUID>
    private var openTurnID: UUID?
    private var cancelledTurnID: UUID?

    public init(conversation: Conversation, devices: [ConversationDevice]) {
        self.conversation = conversation
        self.devices = Dictionary(uniqueKeysWithValues: devices.map { ($0.deviceId, $0) })
        self.nextSequence = 1
        self.seenEventIDs = []
        self.openTurnID = nil
        self.cancelledTurnID = nil
    }

    public func accept(_ event: ConversationEvent) -> ConversationAcceptance {
        if let rejection = envelopeRejection(for: event) {
            return reject(rejection)
        }
        if let rejection = payloadRejection(for: event) {
            return reject(rejection)
        }
        seenEventIDs.insert(event.eventId)
        nextSequence += 1
        applyPayloadState(event)
        return ConversationAcceptance(accepted: true, rejection: nil, nextSequence: nextSequence)
    }

    private func reject(_ rejection: ConversationRejection) -> ConversationAcceptance {
        ConversationAcceptance(accepted: false, rejection: rejection, nextSequence: nextSequence)
    }

    private func envelopeRejection(for event: ConversationEvent) -> ConversationRejection? {
        if event.conversationId != conversation.conversationId {
            return .unknownConversation
        }
        if conversation.state != .active {
            return .conversationClosed
        }
        if seenEventIDs.contains(event.eventId) {
            return .duplicateEvent
        }
        if !conversation.participantIds.contains(event.participantId) {
            return .foreignParticipant
        }
        guard let device = devices[event.deviceId],
            conversation.deviceIds.contains(event.deviceId) else {
            return .foreignDevice
        }
        if device.participantId != event.participantId {
            return .deviceParticipantMismatch
        }
        if event.kind.rawValue != event.payload.kind {
            return .kindMismatch
        }
        if event.sequence != nextSequence {
            return .outOfOrder
        }
        return nil
    }

    private func payloadRejection(for event: ConversationEvent) -> ConversationRejection? {
        switch event.payload {
        case .transcriptPartial(let payload):
            return transcriptRejection(turnId: payload.turnId, isFinal: false)
        case .transcriptFinal(let payload):
            return transcriptRejection(turnId: payload.turnId, isFinal: true)
        case .resume(let payload):
            if cancelledTurnID == nil || payload.resumeFromTurnId != cancelledTurnID {
                return .resumeWithoutCancellation
            }
            return nil
        case .attachment, .toolResult, .cancellation, .error:
            return nil
        }
    }

    private func transcriptRejection(turnId: UUID, isFinal: Bool) -> ConversationRejection? {
        if let cancelledTurnID, turnId == cancelledTurnID {
            return .eventAfterCancellation
        }
        if let openTurnID {
            if turnId != openTurnID {
                return .turnClosed
            }
            return nil
        }
        if isFinal {
            return .finalWithoutPartial
        }
        return nil
    }

    private func applyPayloadState(_ event: ConversationEvent) {
        switch event.payload {
        case .transcriptPartial(let payload):
            openTurnID = payload.turnId
        case .transcriptFinal:
            openTurnID = nil
        case .cancellation(let payload):
            openTurnID = nil
            cancelledTurnID = payload.turnId
        case .resume(let payload):
            openTurnID = payload.turnId
            cancelledTurnID = nil
        case .attachment, .toolResult, .error:
            break
        }
    }
}

public extension JSONDecoder.DateDecodingStrategy {
    static let lifeOSISO8601: JSONDecoder.DateDecodingStrategy = .custom { decoder in
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        let fractional = ISO8601DateFormatter()
        fractional.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = fractional.date(from: raw) {
            return date
        }
        let plain = ISO8601DateFormatter()
        plain.formatOptions = [.withInternetDateTime]
        if let date = plain.date(from: raw) {
            return date
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "invalid ISO8601 date: \\(raw)"
        )
}
}
"""

if __name__ == "__main__":
    sys.exit(main())
