// Generated by scripts/generate_contracts.py; do not edit.
public struct SecretaryContractVersion: Equatable, Sendable {
    public static let current = SecretaryContractVersion()
    public let rawValue = "1.0.0"

    private init() {}
}
