// Generated by scripts/generate_contracts.py; do not edit.
import Foundation

public enum ParticipantKind: String, Codable, Equatable, Sendable {
    case user = "user"
    case agent = "agent"
}

public enum DeviceKind: String, Codable, Equatable, Sendable {
    case ios = "ios"
    case mac = "mac"
    case web = "web"
    case channel = "channel"
}

public enum ChannelKind: String, Codable, Equatable, Sendable {
    case openclawWebchat = "openclaw_webchat"
    case telegram = "telegram"
    case imessage = "imessage"
    case email = "email"
}

public enum ChannelBindingState: String, Codable, Equatable, Sendable {
    case active = "active"
    case revoked = "revoked"
}

public enum ConversationState: String, Codable, Equatable, Sendable {
    case active = "active"
    case cancelled = "cancelled"
    case completed = "completed"
}

public enum ConversationEventKind: String, Codable, Equatable, Sendable {
    case transcriptPartial = "transcript_partial"
    case transcriptFinal = "transcript_final"
    case attachment = "attachment"
    case toolResult = "tool_result"
    case cancellation = "cancellation"
    case resume = "resume"
    case error = "error"
}

public enum ToolResultStatus: String, Codable, Equatable, Sendable {
    case ok = "ok"
    case error = "error"
}

public struct ConversationParticipant: Codable, Equatable, Sendable {
    public let participantId: UUID
    public let kind: ParticipantKind
    public let displayName: String
    public let createdAt: Date

    private enum CodingKeys: String, CodingKey {
        case participantId = "participant_id"
        case kind
        case displayName = "display_name"
        case createdAt = "created_at"
    }
}

public struct ConversationDevice: Codable, Equatable, Sendable {
    public let deviceId: UUID
    public let participantId: UUID
    public let kind: DeviceKind
    public let name: String
    public let createdAt: Date

    private enum CodingKeys: String, CodingKey {
        case deviceId = "device_id"
        case participantId = "participant_id"
        case kind
        case name
        case createdAt = "created_at"
    }
}

public struct ChannelBinding: Codable, Equatable, Sendable {
    public let bindingId: UUID
    public let conversationId: UUID
    public let channelKind: ChannelKind
    public let externalChannelId: String
    public let externalUserId: String
    public let boundAt: Date
    public let state: ChannelBindingState

    private enum CodingKeys: String, CodingKey {
        case bindingId = "binding_id"
        case conversationId = "conversation_id"
        case channelKind = "channel_kind"
        case externalChannelId = "external_channel_id"
        case externalUserId = "external_user_id"
        case boundAt = "bound_at"
        case state
    }
}

public struct Conversation: Codable, Equatable, Sendable {
    public let conversationId: UUID
    public let title: String
    public let participantIds: [UUID]
    public let deviceIds: [UUID]
    public let createdAt: Date
    public let state: ConversationState

    private enum CodingKeys: String, CodingKey {
        case conversationId = "conversation_id"
        case title
        case participantIds = "participant_ids"
        case deviceIds = "device_ids"
        case createdAt = "created_at"
        case state
    }
}

public struct TranscriptPartial: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let text: String
    public let isFinal: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case text
        case isFinal = "is_final"
    }
}

public struct TranscriptFinal: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let text: String
    public let isFinal: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case text
        case isFinal = "is_final"
    }
}

public struct Attachment: Codable, Equatable, Sendable {
    public let kind: String
    public let attachmentId: UUID
    public let mimeType: String
    public let sizeBytes: Int
    public let reference: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case attachmentId = "attachment_id"
        case mimeType = "mime_type"
        case sizeBytes = "size_bytes"
        case reference
    }
}

public struct ToolResult: Codable, Equatable, Sendable {
    public let kind: String
    public let toolCallId: String
    public let toolName: String
    public let status: ToolResultStatus
    public let resultReference: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case toolCallId = "tool_call_id"
        case toolName = "tool_name"
        case status
        case resultReference = "result_reference"
    }
}

public struct Cancellation: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let reason: String

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case reason
    }
}

public struct Resume: Codable, Equatable, Sendable {
    public let kind: String
    public let turnId: UUID
    public let resumeFromTurnId: UUID

    private enum CodingKeys: String, CodingKey {
        case kind
        case turnId = "turn_id"
        case resumeFromTurnId = "resume_from_turn_id"
    }
}

public struct ConversationError: Codable, Equatable, Sendable {
    public let kind: String
    public let code: String
    public let message: String
    public let retryable: Bool

    private enum CodingKeys: String, CodingKey {
        case kind
        case code
        case message
        case retryable
    }
}

public enum ConversationEventPayload: Codable, Equatable, Sendable {
    case transcriptPartial(TranscriptPartial)
    case transcriptFinal(TranscriptFinal)
    case attachment(Attachment)
    case toolResult(ToolResult)
    case cancellation(Cancellation)
    case resume(Resume)
    case error(ConversationError)

    public var kind: String {
        switch self {
        case .transcriptPartial: return "transcript_partial"
        case .transcriptFinal: return "transcript_final"
        case .attachment: return "attachment"
        case .toolResult: return "tool_result"
        case .cancellation: return "cancellation"
        case .resume: return "resume"
        case .error: return "error"
        }
    }

    private enum CodingKeys: String, CodingKey {
        case kind
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let kind = try container.decode(String.self, forKey: .kind)
        switch kind {
        case "transcript_partial":
            self = .transcriptPartial(try TranscriptPartial(from: decoder))
        case "transcript_final":
            self = .transcriptFinal(try TranscriptFinal(from: decoder))
        case "attachment":
            self = .attachment(try Attachment(from: decoder))
        case "tool_result":
            self = .toolResult(try ToolResult(from: decoder))
        case "cancellation":
            self = .cancellation(try Cancellation(from: decoder))
        case "resume":
            self = .resume(try Resume(from: decoder))
        case "error":
            self = .error(try ConversationError(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .kind,
                in: container,
                debugDescription: "unknown conversation payload kind: \(kind)"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .transcriptPartial(let payload):
            try payload.encode(to: encoder)
        case .transcriptFinal(let payload):
            try payload.encode(to: encoder)
        case .attachment(let payload):
            try payload.encode(to: encoder)
        case .toolResult(let payload):
            try payload.encode(to: encoder)
        case .cancellation(let payload):
            try payload.encode(to: encoder)
        case .resume(let payload):
            try payload.encode(to: encoder)
        case .error(let payload):
            try payload.encode(to: encoder)
        }
    }
}

public struct ConversationEvent: Codable, Equatable, Sendable {
    public let eventId: UUID
    public let conversationId: UUID
    public let participantId: UUID
    public let deviceId: UUID
    public let sequence: Int
    public let occurredAt: Date
    public let kind: ConversationEventKind
    public let payload: ConversationEventPayload

    private enum CodingKeys: String, CodingKey {
        case eventId = "event_id"
        case conversationId = "conversation_id"
        case participantId = "participant_id"
        case deviceId = "device_id"
        case sequence
        case occurredAt = "occurred_at"
        case kind
        case payload
    }
}

public enum ConversationRejection: String, Codable, Equatable, Sendable {
    case unknownConversation = "unknown_conversation"
    case conversationClosed = "conversation_closed"
    case duplicateEvent = "duplicate_event"
    case outOfOrder = "out_of_order"
    case foreignParticipant = "foreign_participant"
    case foreignDevice = "foreign_device"
    case deviceParticipantMismatch = "device_participant_mismatch"
    case kindMismatch = "kind_mismatch"
    case finalWithoutPartial = "final_without_partial"
    case turnClosed = "turn_closed"
    case eventAfterCancellation = "event_after_cancellation"
    case resumeWithoutCancellation = "resume_without_cancellation"
}

public struct ConversationAcceptance: Codable, Equatable, Sendable {
    public let accepted: Bool
    public let rejection: ConversationRejection?
    public let nextSequence: Int

    private enum CodingKeys: String, CodingKey {
        case accepted
        case rejection
        case nextSequence = "next_sequence"
    }
}

public final class ConversationJournal {
    private let conversation: Conversation
    private let devices: [UUID: ConversationDevice]
    private var nextSequence: Int
    private var seenEventIDs: Set<UUID>
    private var openTurnID: UUID?
    private var cancelledTurnID: UUID?

    public init(conversation: Conversation, devices: [ConversationDevice]) {
        self.conversation = conversation
        self.devices = Dictionary(uniqueKeysWithValues: devices.map { ($0.deviceId, $0) })
        self.nextSequence = 1
        self.seenEventIDs = []
        self.openTurnID = nil
        self.cancelledTurnID = nil
    }

    public func accept(_ event: ConversationEvent) -> ConversationAcceptance {
        if let rejection = envelopeRejection(for: event) {
            return reject(rejection)
        }
        if let rejection = payloadRejection(for: event) {
            return reject(rejection)
        }
        seenEventIDs.insert(event.eventId)
        nextSequence += 1
        applyPayloadState(event)
        return ConversationAcceptance(accepted: true, rejection: nil, nextSequence: nextSequence)
    }

    private func reject(_ rejection: ConversationRejection) -> ConversationAcceptance {
        ConversationAcceptance(accepted: false, rejection: rejection, nextSequence: nextSequence)
    }

    private func envelopeRejection(for event: ConversationEvent) -> ConversationRejection? {
        if event.conversationId != conversation.conversationId {
            return .unknownConversation
        }
        if conversation.state != .active {
            return .conversationClosed
        }
        if seenEventIDs.contains(event.eventId) {
            return .duplicateEvent
        }
        if !conversation.participantIds.contains(event.participantId) {
            return .foreignParticipant
        }
        guard let device = devices[event.deviceId],
            conversation.deviceIds.contains(event.deviceId) else {
            return .foreignDevice
        }
        if device.participantId != event.participantId {
            return .deviceParticipantMismatch
        }
        if event.kind.rawValue != event.payload.kind {
            return .kindMismatch
        }
        if event.sequence != nextSequence {
            return .outOfOrder
        }
        return nil
    }

    private func payloadRejection(for event: ConversationEvent) -> ConversationRejection? {
        switch event.payload {
        case .transcriptPartial(let payload):
            return transcriptRejection(turnId: payload.turnId, isFinal: false)
        case .transcriptFinal(let payload):
            return transcriptRejection(turnId: payload.turnId, isFinal: true)
        case .resume(let payload):
            if cancelledTurnID == nil || payload.resumeFromTurnId != cancelledTurnID {
                return .resumeWithoutCancellation
            }
            return nil
        case .attachment, .toolResult, .cancellation, .error:
            return nil
        }
    }

    private func transcriptRejection(turnId: UUID, isFinal: Bool) -> ConversationRejection? {
        if let cancelledTurnID, turnId == cancelledTurnID {
            return .eventAfterCancellation
        }
        if let openTurnID {
            if turnId != openTurnID {
                return .turnClosed
            }
            return nil
        }
        if isFinal {
            return .finalWithoutPartial
        }
        return nil
    }

    private func applyPayloadState(_ event: ConversationEvent) {
        switch event.payload {
        case .transcriptPartial(let payload):
            openTurnID = payload.turnId
        case .transcriptFinal:
            openTurnID = nil
        case .cancellation(let payload):
            openTurnID = nil
            cancelledTurnID = payload.turnId
        case .resume(let payload):
            openTurnID = payload.turnId
            cancelledTurnID = nil
        case .attachment, .toolResult, .error:
            break
        }
    }
}

public extension JSONDecoder.DateDecodingStrategy {
    static let lifeOSISO8601: JSONDecoder.DateDecodingStrategy = .custom { decoder in
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        let fractional = ISO8601DateFormatter()
        fractional.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = fractional.date(from: raw) {
            return date
        }
        let plain = ISO8601DateFormatter()
        plain.formatOptions = [.withInternetDateTime]
        if let date = plain.date(from: raw) {
            return date
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "invalid ISO8601 date: \(raw)"
        )
}
}
